### ISSUE TITLE
Stop it men

### ISSUE THREAD

**Issue by bukan-jojo** [Zhirrr/Zhirrr-Api#11]
Jangan memudahkan kang copas

Bot udah pasaran, sekarang ini juga?

**Comment by Zhirrr** [comment]
Emng knapa mank ?

**Comment by RizqiTatsumaki** [comment]
wow nampaknya akan terjadi pergelutan

**Comment by Zhirrr** [comment]
Toh emng Saia buat repo ini buat smua orang gratis

**Comment by Zhirrr** [comment]
Selagi buat kebaikan mah gapapa, toh Saia juga udh ngasih di readme nya jagan diperjualbelikan :v, Dosa tanggung sendiri kwkwkwkwkwkw

**Comment by Zhirrr** [comment]
> wow nampaknya akan terjadi pergelutan

Owh, tentu saja Tydack 😂

**Comment by Zhirrr** [comment]
Ane close yak dari pada bergelut ntar klean

**Comment by bukan-jojo** [comment]
> Selagi buat kebaikan mah gapapa, toh Saia juga udh ngasih di readme nya jagan diperjualbelikan :v, Dosa tanggung sendiri kwkwkwkwkwkw

Berbuat baik nya sih udah bener, tapi merugikan orang yang menjaga cara bikin api nya yang susah bukan asal copas, apalagi yang jualan key kayak vhtear, mhankbarbar dll seperti saya:v

**Comment by FERDIZ-afk** [comment]
Ok

**Comment by FERDIZ-afk** [comment]
Gwe nyimak ae ngap hehe

**Comment by Zhirrr** [comment]
> > Selagi buat kebaikan mah gapapa, toh Saia juga udh ngasih di readme nya jagan diperjualbelikan :v, Dosa tanggung sendiri kwkwkwkwkwkw
> 
> Berbuat baik nya sih udah bener, tapi merugikan orang yang menjaga cara bikin api nya yang susah bukan asal copas, apalagi yang jualan key kayak vhtear, mhankbarbar dll seperti saya:v

Toh Saia juga buat sndiri, juga Ama temen saia, emng ini api buat nya gak capek mank ? Sama aja kek lainnya, tujuan Saia buat api ini untuk bantu orang lain untuk belajar, karena banyak yg Wea Saia minta dibuatin :v

**Comment by Zhirrr** [comment]
> > Selagi buat kebaikan mah gapapa, toh Saia juga udh ngasih di readme nya jagan diperjualbelikan :v, Dosa tanggung sendiri kwkwkwkwkwkw
> 
> Berbuat baik nya sih udah bener, tapi merugikan orang yang menjaga cara bikin api nya yang susah bukan asal copas, apalagi yang jualan key kayak vhtear, mhankbarbar dll seperti saya:v

Kalo mau jualan, silakan aja atuh mank, rejeki dah ada yang ngatur 👍
